import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import GeneratorForm from '../components/form/GeneratorForm'
import SeasonPageAccent from '../components/form/SeasonPageAccent'
import MoodPageAccent from '../components/form/MoodPageAccent'
import { generateDestinations } from '../services/destinationsApi'
import { normalizeDestination } from '../utils/normalizeDestination'
import { useActiveSeason } from '../context/SeasonContext'
import { SEASON_THEMES } from '../data/seasonThemes'
import { resolvePageSeason } from '../utils/resolvePageSeason'
import { readCachedRemaining, writeCachedRemaining } from '../utils/generationUsage'

const DEPARTURE_AIRPORT_ID = 1
const DEPARTURE_AIRPORT_IATA = 'STN'
const SESSION_KEY = 'litl_last_result'

export default function GeneratorPage() {
  const navigate = useNavigate()

  const [status, setStatus]     = useState('idle') // idle | loading | error | empty
  const [errorMsg, setErrorMsg] = useState('')
  const [tripInput, setTripInput] = useState(null)
  // Sticky for the session once hit — generation quota only resets monthly server-side.
  const [generationLimitReached, setGenerationLimitReached] = useState(false)
  // Best-known reveal count for the usage badge — purely informational,
  // never used to gate the form (that's generationLimitReached, server-driven).
  const [remainingGenerations, setRemainingGenerations] = useState(() => readCachedRemaining())

  // formSeason / formMood: drive the external page accents
  const [formSeason, setFormSeason] = useState('')
  const [formMood,   setFormMood]   = useState('')

  const { season, setSeason } = useActiveSeason()
  const pageSeasonKey = resolvePageSeason(tripInput?.season || season)
  const pageTheme = SEASON_THEMES[pageSeasonKey]

  function handleSeasonChange(s) {
    setSeason(s)
    setFormSeason(s)
  }

  function handleMoodChange(m) {
    setFormMood(m)
  }

  async function handleSubmit(formValues) {
    setStatus('loading')
    setErrorMsg('')

    try {
      const budgetPerPerson = Number(formValues.budget)
      const payload = {
        departure_airport_id: DEPARTURE_AIRPORT_ID,
        budget: budgetPerPerson * formValues.travellers,
        budget_per_person: budgetPerPerson,
        travellers: formValues.travellers,
        trip_type_slug: formValues.mood,
        season: formValues.season,
      }

      const res = await generateDestinations(payload)
      const dests = res.data?.data?.destinations ?? []
      const remainingGenerations = res.data?.data?.meta?.remaining_generations ?? null

      // Refresh the usage badge with the freshest known count — this holds
      // true whether or not a destination was actually matched this time.
      if (remainingGenerations != null) {
        setRemainingGenerations(remainingGenerations)
        writeCachedRemaining(remainingGenerations)
      }

      if (dests.length === 0) {
        setStatus('empty')
        return
      }

      const firstDest = normalizeDestination(dests[0])

      // Dates are generated by the backend — read them from the normalised destination
      const tripInputData = {
        travellers: formValues.travellers,
        departureDate: firstDest.departure_date,
        returnDate: firstDest.return_date,
        originIata: DEPARTURE_AIRPORT_IATA,
        season: firstDest.season || formValues.season || '',
      }
      setTripInput(tripInputData)

      // Persist to sessionStorage as fallback for page refresh on result page
      try {
        sessionStorage.setItem(SESSION_KEY, JSON.stringify({
          destination: firstDest,
          tripInput: tripInputData,
          remainingGenerations,
        }))
      } catch { /* ignore storage errors */ }

      // Navigate to dedicated result page
      navigate('/travel/result', {
        state: { destination: firstDest, tripInput: tripInputData, remainingGenerations },
      })
    } catch (err) {
      if (err?.response?.data?.code === 'GENERATION_LIMIT_REACHED') {
        setGenerationLimitReached(true)
        setRemainingGenerations(0)
        writeCachedRemaining(0)
      }
      setErrorMsg(
        err?.response?.data?.message || 'Something went wrong. Please try again.'
      )
      setStatus('error')
    }
  }

  return (
    <div
      className="min-h-screen"
      style={{ background: `${pageTheme.pageGradient}, #fff7ed` }}
    >
      {/* Orange gradient page header */}
      <header style={{ background: 'linear-gradient(135deg, #c2410c 0%, #ea580c 45%, #f97316 80%, #fb923c 100%)' }}>
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-6 relative overflow-hidden">
          <div
            aria-hidden="true"
            className="absolute -top-8 right-8 w-32 h-32 rounded-full pointer-events-none"
            style={{
              background: 'radial-gradient(circle, rgba(251,191,36,0.3) 0%, transparent 70%)',
              animation: 'sunGlow 7s ease-in-out infinite',
            }}
          />
          <div className="relative">
            <h1 className="text-2xl font-bold text-white tracking-tight">Leave It To Luck</h1>
            <p className="text-sm mt-1" style={{ color: 'rgba(255,255,255,0.7)' }}>
              Tell us your budget and vibe — we'll handle the rest
            </p>
          </div>
        </div>
      </header>

      {/* Main content */}
      <main
        className="max-w-4xl mx-auto px-4 sm:px-6 py-8 space-y-6"
        style={{ animation: 'fadeInUp 0.45s ease forwards' }}
      >
        {/* Form section — mood accent left, season accent right, form on top */}
        <div className="relative" style={{ overflow: 'visible' }}>

          {/* MoodPageAccent: enters from left, floats above form upper-left corner */}
          {formMood && (
            <div
              className="absolute hidden sm:block pointer-events-none"
              style={{ top: '-60px', left: '-70px', zIndex: 30 }}
            >
              <MoodPageAccent key={formMood} mood={formMood} />
            </div>
          )}

          {/* SeasonPageAccent: enters from right, floats above form upper-right corner.
              scaleX(-1) mirrors the illustration + reverses the entrance animation direction. */}
          {formSeason && (
            <div
              className="absolute hidden sm:block pointer-events-none"
              style={{ top: '-60px', right: '-70px', zIndex: 30, transform: 'scaleX(-1)' }}
            >
              <SeasonPageAccent key={formSeason} season={formSeason} />
            </div>
          )}

          <div style={{ position: 'relative', zIndex: 20 }}>
            <GeneratorForm
              onSubmit={handleSubmit}
              isLoading={status === 'loading'}
              disabled={generationLimitReached}
              onSeasonPreview={handleSeasonChange}
              onMoodPreview={handleMoodChange}
              activeSeason={season}
              pageTheme={pageTheme}
              remainingGenerations={remainingGenerations}
            />
          </div>
        </div>

        {/* Inline status messages — only for error/empty (success navigates away) */}
        {status === 'error' && (
          <div
            className="rounded-2xl p-4 text-sm font-medium"
            style={{ backgroundColor: '#fff1f2', border: '1px solid #fecdd3', color: '#be123c' }}
          >
            {errorMsg || 'Something went wrong. Please try again.'}
          </div>
        )}
        {status === 'empty' && (
          <div
            className="rounded-2xl p-4 text-sm"
            style={{ backgroundColor: 'rgba(255,255,255,0.8)', border: '1px solid rgba(251,146,60,0.2)', color: '#78716c' }}
          >
            No destinations found for your preferences. Try adjusting your budget, mood, or season.
          </div>
        )}
      </main>
    </div>
  )
}
