import { useState } from 'react'
import { Link } from 'react-router-dom'
import GeneratedWorldMap from '../components/stats/GeneratedWorldMap'
import { WORLD_MAP_DESTINATIONS, MOOD_COLORS } from '../data/worldMapStats'

const sorted = [...WORLD_MAP_DESTINATIONS].sort((a, b) => a.rank - b.rank)

export default function WorldMapPage() {
  const [tooltip, setTooltip] = useState(null) // { dest, x, y }

  const handleMarkerHover = (dest, event) => {
    setTooltip(dest ? { dest, x: event.clientX, y: event.clientY } : null)
  }

  return (
    <div className="min-h-screen bg-slate-50">
      <header className="bg-white border-b border-slate-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-5">
          <div className="flex items-center gap-3">
            <Link
              to="/stats"
              className="text-sm text-slate-500 hover:text-slate-800 transition-colors duration-150"
            >
              ← Stats
            </Link>
            <span className="w-px h-4 bg-slate-200" />
            <div>
              <h1 className="text-2xl font-semibold text-slate-900 tracking-tight">World Map</h1>
              <p className="text-sm text-slate-500 mt-0.5">
                Destinations generated by LITL travelers
              </p>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">

          {/* Map card */}
          <div
            className="lg:col-span-2 rounded-2xl overflow-hidden border border-blue-100"
            style={{ background: 'linear-gradient(160deg, #f0f9ff 0%, #e0f2fe 45%, #dbeafe 100%)' }}
          >
            <GeneratedWorldMap
              highlightCity={tooltip?.dest?.city ?? null}
              onMarkerHover={handleMarkerHover}
            />
            {/* Mood legend */}
            <div className="px-6 pb-5 flex items-center gap-5 flex-wrap">
              {Object.entries(MOOD_COLORS).map(([mood, color]) => (
                <span key={mood} className="flex items-center gap-1.5 text-xs text-slate-600">
                  <span className="w-2 h-2 rounded-full shrink-0" style={{ backgroundColor: color }} />
                  {mood}
                </span>
              ))}
            </div>
          </div>

          {/* Ranked destinations list */}
          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="px-6 py-4 border-b border-slate-100">
              <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">
                Top Destinations
              </p>
            </div>
            <div className="overflow-y-auto" style={{ maxHeight: 460 }}>
              {sorted.map((dest) => {
                const isActive = tooltip?.dest?.city === dest.city
                const color = MOOD_COLORS[dest.topMood] ?? '#3b82f6'
                return (
                  <div
                    key={dest.city}
                    className={`flex items-center gap-3 px-6 py-3 transition-colors duration-100 ${
                      isActive ? 'bg-blue-50' : 'hover:bg-slate-50'
                    }`}
                  >
                    <span className="text-xs font-bold text-slate-300 w-5 shrink-0 tabular-nums">
                      {dest.rank}
                    </span>
                    <span
                      className="w-2 h-2 rounded-full shrink-0"
                      style={{ backgroundColor: color }}
                    />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-semibold text-slate-900 truncate">{dest.city}</p>
                      <p className="text-xs text-slate-400 truncate">{dest.country}</p>
                    </div>
                    <span className="text-xs font-bold text-slate-400 shrink-0 tabular-nums">
                      {dest.generatedCount}
                    </span>
                  </div>
                )
              })}
            </div>
          </div>

        </div>
      </main>

      {/* Floating tooltip */}
      {tooltip && (
        <div
          className="fixed z-50 pointer-events-none"
          style={{ left: tooltip.x + 16, top: tooltip.y - 10 }}
        >
          <div className="bg-white border border-slate-200 rounded-xl px-4 py-3 shadow-lg text-sm max-w-48">
            <p className="font-bold text-slate-900 leading-snug">
              {tooltip.dest.city}, {tooltip.dest.country}
            </p>
            <p className="text-slate-500 text-xs mt-1.5">
              Generated {tooltip.dest.generatedCount}×
            </p>
            <p className="text-slate-400 text-xs">#{tooltip.dest.rank} trending</p>
            <p
              className="text-xs font-semibold mt-1.5"
              style={{ color: MOOD_COLORS[tooltip.dest.topMood] }}
            >
              {tooltip.dest.topMood}
            </p>
          </div>
        </div>
      )}
    </div>
  )
}
